/*
 * Copyright (C) 2021 University Hospital Bonn - All Rights Reserved You may use, distribute and
 * modify this code under the GPL 3 license. THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT
 * PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR
 * OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
 * IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH
 * YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR
 * OR CORRECTION. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY
 * COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE,
 * BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA
 * OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE
 * PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES. You should have received a copy of the GPL 3 license with *
 * this file. If not, visit http://www.gnu.de/documents/gpl-3.0.en.html
 */

package de.medizininformatik_initiative.process.report;

public interface ConstantsReport
{
	String PROCESS_NUM_NAME_BASE = "netzwerk-universitaetsmedizinde_";
	String PROCESS_NUM_URI_BASE = "http://netzwerk-universitaetsmedizin.de/bpe/Process/";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_NETWORK_OF_UNIVERSITY_MEDICINE_CONSORTIUM = "netzwerk-universitaetsmedizin.de";

	String PROCESS_NAME_REPORT_AUTOSTART = "reportAutostart";
	String PROCESS_NAME_REPORT_RECEIVE = "reportReceive";
	String PROCESS_NAME_REPORT_SEND = "reportSend";

	String PROCESS_NAME_FULL_REPORT_AUTOSTART = PROCESS_NUM_NAME_BASE + PROCESS_NAME_REPORT_AUTOSTART;
	String PROCESS_NAME_FULL_REPORT_RECEIVE = PROCESS_NUM_NAME_BASE + PROCESS_NAME_REPORT_RECEIVE;
	String PROCESS_NAME_FULL_REPORT_SEND = PROCESS_NUM_NAME_BASE + PROCESS_NAME_REPORT_SEND;

	String PROFILE_TASK_REPORT_AUTOSTART_START = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/task-report-autostart-start";
	String PROFILE_TASK_REPORT_AUTOSTART_START_PROCESS_URI = PROCESS_NUM_URI_BASE + PROCESS_NAME_REPORT_AUTOSTART;
	String PROFILE_TASK_REPORT_AUTOSTART_START_MESSAGE_NAME = "dashboardReportAutostartStart";

	String PROFILE_TASK_REPORT_AUTOSTART_STOP = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/task-report-autostart-stop";
	String PROFILE_TASK_REPORT_AUTOSTART_STOP_PROCESS_URI = PROCESS_NUM_URI_BASE + PROCESS_NAME_REPORT_AUTOSTART;
	String PROFILE_TASK_REPORT_AUTOSTART_STOP_MESSAGE_NAME = "dashboardReportAutostartStop";

	String PROFILE_TASK_REPORT_SEND_START = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/task-report-send-start";
	String PROFILE_TASK_REPORT_SEND_START_PROCESS_URI = PROCESS_NUM_URI_BASE + PROCESS_NAME_REPORT_SEND;
	String PROFILE_TASK_REPORT_SEND_START_MESSAGE_NAME = "dashboardReportSendStart";

	String PROFILE_TASK_REPORT_SEND = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/task-report-send";
	String PROFILE_TASK_REPORT_SEND_PROCESS_URI = PROCESS_NUM_URI_BASE + PROCESS_NAME_REPORT_SEND;
	String PROFILE_TASK_REPORT_SEND_MESSAGE_NAME = "dashboardReportSend";

	String PROFILE_TASK_REPORT_RECEIVE = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/task-report-receive";
	String PROFILE_TASK_REPORT_RECEIVE_PROCESS_URI = PROCESS_NUM_URI_BASE + PROCESS_NAME_REPORT_RECEIVE;
	String PROFILE_TASK_REPORT_RECEIVE_MESSAGE_NAME = "dashboardReportReceive";

	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_APPROVAL = "reportApproval";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_TIMEOUT = "reportTimeout";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_TIMEOUT_ERROR = "ddpTimeoutError";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_OUTPUT_APPROVED = "approvalVote";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_APPROVAL_TIMEOUT_ERROR = "approvalTimeoutError";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_JSON = "reportJson";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_JSON_RESPONSE_REFERENCE = "reportJsonResponseReference";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_APPROVAL_QUESTIONNAIRERESPONSE_REFERENCE = "reportApprovalQuestionnaireResponseReference";
	String BPMN_EXECUTION_VARIABLE_DASHBOARD_REPORT_DDP_BINARY = "reportSearchBundle";

	String BPMN_EXECUTION_VARIABLE_REPORT_TIMER_INTERVAL = "reportTimerInterval";
	String BPMN_EXECUTION_VARIABLE_REPORT_FIRST_EXECUTION = "reportFirstExecution";
	String BPMN_EXECUTION_VARIABLE_REPORT_FIRST_EXECUTION_DELAYED = "reportFirstExecutionDelayed";
	String BPMN_EXECUTION_VARIABLE_REPORT_RECEIVE_ERROR = "reportReceiveError";
	String BPMN_EXECUTION_VARIABLE_REPORT_RECEIVE_ERROR_MESSAGE = "reportReceiveErrorMessage";

	String CODESYSTEM_REPORT = "http://netzwerk-universitaetsmedizin.de/fhir/CodeSystem/report";

	String CODESYSTEM_REPORT_VALUE_SEARCH_BUNDLE = "search-bundle-v";
	String CODESYSTEM_REPORT_VALUE_SEARCH_BUNDLE_RESPONSE_REFERENCE = "search-bundle-response-reference";
	String CODESYSTEM_REPORT_VALUE_REPORT_STATUS = "report-status";
	String CODESYSTEM_REPORT_VALUE_TIMER_INTERVAL = "timer-interval";
	String CODESYSTEM_REPORT_VALUE_FIRST_EXECUTION = "first-execution";
	String CODESYSTEM_REPORT_VALUE_HRP_IDENTIFIER = "hrp-identifier";

	String CODESYSTEM_REPORT_STATUS = "http://netzwerk-universitaetsmedizin.de/fhir/CodeSystem/report-status";
	String CODESYSTEM_REPORT_STATUS_VALUE_NOT_ALLOWED = "not-allowed";
	String CODESYSTEM_REPORT_STATUS_VALUE_NOT_REACHABLE = "not-reachable";
	String CODESYSTEM_REPORT_STATUS_VALUE_RECEIPT_MISSING = "receipt-missing";
	String CODESYSTEM_REPORT_STATUS_VALUE_RECEIPT_OK = "receipt-ok";
	String CODESYSTEM_REPORT_STATUS_VALUE_RECEIPT_ERROR = "receipt-error";
	String CODESYSTEM_REPORT_STATUS_VALUE_RECEIVE_OK = "receive-ok";
	String CODESYSTEM_REPORT_STATUS_VALUE_RECEIVE_ERROR = "receive-error";

	String PROFILE_REPORT_SEARCH_BUNDLE_RESPONSE = "http://netzwerk-universitaetsmedizin.de/fhir/Bundle/search-bundle-response-report";
	String EXTENSION_REPORT_STATUS_ERROR_URL = "http://netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/extension-report-status-error";

	String REPORT_TIMER_INTERVAL_DEFAULT_VALUE = "P1D";

	String CODESYSTEM_VOTING_PROCESS = "http://ukbonn.de/fhir/CodeSystem/approve-dashboard-binary";
	String CODESYSTEM_VOTING_PROCESS_VALUE_BINARY_QUESTION = "binary-question";

	String CODESYSTEM_REPORT_BACKEND_TYPE = "http://netzwerk-universitaetsmedizin.de/fhir/CodeSystem/backend-type";
	String CODESYSTEM_REPORT_BACKEND_TYPE_VALUE = "backend-type";
}
